### ISSUE TITLE
SignalFlow computations don't automatically reconnect

### ISSUE THREAD

**Issue by mpetazzoni** [signalfx/signalfx-ruby#16]
If the backend service is restarted/upgraded on the SignalFx side and the connection is closed, the Ruby client library should automatically and transparently re-execute running SignalFlow computations from their last known received timestamp.

**Comment by mpetazzoni** [comment]
Hey @keitwb isn't this working now?

**Comment by jtmal-signalfx** [comment]
There hasn't been any new messages here for some time now, so I'm closing. If it's still needed, please let me know.
