### ISSUE TITLE
signalfx 2.0 to rubygems.org

### ISSUE THREAD

**Issue by stacybird** [signalfx/signalfx-ruby#17]
Love the update, thanks!
latest version rubygems knows about is 1.0.2 : https://rubygems.org/gems/signalfx/versions

**Comment by molner** [comment]
Thanks for bringing this to our attention @stacybird! Rubygems has been updated for v2.0.1.

**Comment by stacybird** [comment]
@molner Thanks!  Can't wait to take it for a spin.
