### ISSUE TITLE
Improve Logging (Replace 'puts')

### ISSUE THREAD

**Issue by JamesFrost** [signalfx/signalfx-ruby#35]
The current use of `puts` inside the gem is problematic.

You can't control what gets logged, or where the logs go. Whenever our application gets loaded, the gem prints something to stdout. This is filling up our logs.

A potential solution would be to allow users to pass an instance of the [standard library Logger class](https://ruby-doc.org/stdlib-2.6/libdoc/logger/rdoc/Logger.html).

**Comment by mpetazzoni** [comment]
@JamesFrost Thanks for the feedback! This could definitely be improved.

Would you be able to send a PR? Happy to review it once you do.
