### ISSUE TITLE
Recommend renaming `send` method to something else that's not a core Ruby method

### ISSUE THREAD

**Issue by sophylee** [signalfx/signalfx-ruby#4]
The method used for incrementing metrics is `send`, which is the same as the Ruby [send method](http://ruby-doc.org/core-2.3.0/Object.html#method-i-send). This seems prone to bugs / confusion / incompatibilities, sort of like writing your own `each` method. Can `send` be named something else?

**Comment by cep21** [comment]
This sounds reasonable.  If you're willing to submit a pull request I would be happy to review it.  I think it's reasonable to just bump the primary version number when renaming.  Otherwise will have to queue this request behind my worklog.

**Comment by caldwecr** [comment]
👍

**Comment by hslee16** [comment]
+1

**Comment by caldwecr** [comment]
How about calling it `#transmit`

**Comment by benmullin333** [comment]
@sophylee where's the PR? ;)

**Comment by jtmal-signalfx** [comment]
There hasn't been any new messages here for some time now, so I'm closing. If it's still needed, please let me know.
