### ISSUE TITLE
Upgrade  tzinfo to 2.0.0

### ISSUE THREAD

**Issue by matias2681** [signalfx/signalfx-ruby#40]
While trying to upgrade our fluentd to 1.7.3 I got this error.
```
/usr/local/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': 
Unable to activate activesupport-6.0.0, because tzinfo-2.0.0 conflicts with 
tzinfo (~> 1.1) (Gem::ConflictError)
```

Basically, fluentd 1.7.3 needs `tzinfo 2.0.0`
https://github.com/fluent/fluentd/blob/v1.7.3/fluentd.gemspec#L27
and SignalFx requires `tzinfo 1.1`
https://github.com/signalfx/signalfx-ruby/blob/master/Gemfile.lock#L17

Any chance to provide some compatibility with `tzinfo 2.0.0`? 
We would like to upgrade fluentd and keep our custom SignalFx plugin working too.

**Comment by jtmal-signalfx** [comment]
Hey, we don't rely on `tzinfo` directly and `Gemfile.lock` is now removed, so this should be fixed.
