### ISSUE TITLE
curious - why i18n specifically 1.1.0?

### ISSUE THREAD

**Issue by petertseng** [signalfx/signalfx-ruby#47]
In https://github.com/signalfx/signalfx-ruby/pull/43, the gemspec was made to require i18n gem specifically at version 1.1.0. May I ask (out of curiosity only) why that would be? Were there any problems discovered with using other versions of i18n gem?

Since this is not causing any version problems for me, this question is for curiosity only and not because something is broken. So it can be treated with accordingly low priority. You don't need to remove the requirement in order to close this issue, just an explanation suffices. Thanks.

**Comment by rmfitzpatrick** [comment]
Apologies for the radio silence on this front.  I believe this was an oversight that has recently [been resolved](https://github.com/signalfx/signalfx-ruby/pull/56) with the release of https://rubygems.org/gems/signalfx/versions/3.1.1.

Thank you very much for your patience.
