### ISSUE TITLE
Rename deprecated `Conf`

### ISSUE THREAD

**Issue by sophylee** [signalfx/signalfx-ruby#6]
After installing the gem, every time I start Rails I now get the warning 

```
...gems/signalfx-0.1.0/lib/signalfx/conf.rb:3:in `<top (required)>': Use RbConfig instead of obsolete and deprecated Config.

https://github.com/signalfx/signalfx-ruby/blob/master/lib/signalfx/conf.rb#L3
```

`Config` has been deprecated since Ruby 1.9.2 so it would be great to replace this with `RbConfig`.

**Comment by sophylee** [comment]
https://github.com/signalfx/signalfx-ruby/blob/master/lib/signalfx/conf.rb#L3

**Comment by cep21** [comment]
This sounds reasonable.  If you're willing to submit a pull request I would be happy to review it.  Otherwise will have to queue this request behind my worklog.  I don't code ruby in my day-to-day code so I'm not very familiar with best practices in the language.
